spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/my_makeup_database
spring.datasource.username=admin
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

cloudinary.cloud-name=dk85s3hmq
cloudinary.api-key=774938667124636
cloudinary.api-secret=Mk_16isFpwSH0TvRZGiIIqoF9y0
